Initial Docker support (#167)
* Add class-validator

From root:
npx lerna add class-validator --scope @graphmarket/gateway

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Add some dockerfiles. See details below

From root:

docker-compose build
docker-compose build --no cache

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* mini fix for npm prune

* Use node:lts and do not copy package-lock

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Use npx ts-node as a workaround to compile (HAS BUGS! See details)

Command npm run build exits with errors presumably related to dependencies and typings.
We have attempted to move tsconfig.common.ts from the project's root to the package. This makes npm run build execute with success; however, we cannot use this solution as it breaks modularity.
In other words, it seems that the culprit of the problem is
"extends": "../../tsconfig.common.json"

As a workaround, Carlo suggested we temporarily use:
npx ts-node -r tsconfig-paths/register src/bootstrap.ts

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Fix typo (naming consistency)

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Add several dockerfiles (BUGS! See commit f93aa694)

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Sketch some docker-compose (Has an error: see details)

Problems with authentications:

src/config/env.ts(2,21): error TS7016: Could not find a declaration file for module 'convert-units'. '/graphmarket/packages/graphmarket-service-authentications/node_modules/convert-units/lib/index.js' implicitly has an 'any' type.

Try `npm i --save-dev @types/convert-units` if it exists or add a new declaration (.d.ts) file containing `declare module 'convert-units';`

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Fix 339c6edd

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Change network addresses

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Dockerfiles in development mode

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* More logging to facilitate debugging

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Add missing dependencies: pg and ioredis

Fixes https://github.com/carlocorradini/graphmarket/issues/155

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Remove custom networks + fix typeorm/ioredis

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Update docker-compose for production to reflect changes made so far to the one for development

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Remove useless comments

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Remove cors

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

* Bump helpers version

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

Co-authored-by: Carlo <carlo.ita98@gmail.com>